const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      link: {
        type: 'doc',
        id: 'intro/intro',
      },
      items: [
        'intro/what-is-grizzly',
        {
          type: 'category',
          label: 'Installation',
          link: {
            type: 'doc',
            id: 'intro/installation',
          },
          items: [
            'intro/installation/lunar'
          ],
        },
        'intro/quick-start',
        'intro/recommended-mods',
      ],
    },

    {
      type: 'autogenerated',
      dirName: 'features',
    },

    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
  ],
};

export default sidebars;