#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0) uniform sampler2D inputSampler;
layout(binding = 1, rgba8) uniform writeonly image2D outputImage;

layout(push_constant) uniform PC {
    float offset;
};

void main() {
    ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(outputImage);
    if (pos.x >= size.x || pos.y >= size.y) return;

    vec2 uv = (vec2(pos) + 0.5) / vec2(size);
    vec2 texelSize = 1.0 / vec2(textureSize(inputSampler, 0));
    vec2 halfpixel = texelSize / 2.0;

    vec4 sum = texture(inputSampler, uv + vec2(-halfpixel.x * 2.0, 0.0) * offset);
    sum += texture(inputSampler, uv + vec2(-halfpixel.x, halfpixel.y) * offset) * 2.0;
    sum += texture(inputSampler, uv + vec2(0.0, halfpixel.y * 2.0) * offset);
    sum += texture(inputSampler, uv + vec2(halfpixel.x, halfpixel.y) * offset) * 2.0;
    sum += texture(inputSampler, uv + vec2(halfpixel.x * 2.0, 0.0) * offset);
    sum += texture(inputSampler, uv + vec2(halfpixel.x, -halfpixel.y) * offset) * 2.0;
    sum += texture(inputSampler, uv + vec2(0.0, -halfpixel.y * 2.0) * offset);
    sum += texture(inputSampler, uv + vec2(-halfpixel.x, -halfpixel.y) * offset) * 2.0;

    imageStore(outputImage, pos, vec4((sum / 12.0).rgb, 1.0));
}
